name: deploy
on:
  push:
    branches-ignore:
      - gh-pages
jobs:
  rmd-render-job:
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-22.04, r: '4.1.0'}
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
      - name: Setup quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.2.335
      - name: Install linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libxml2-dev libssl-dev libcurl4-openssl-dev libudunits2-dev libopenblas-base
      - name: Setup quarto
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            any::dplyr
            any::tidyr
            any::stringr
            any::htmlTable
            any::kableExtra
            any::formattable
            any::DT
            any::reactable
            any::ggplot2
            any::highcharter
            any::plotly
            any::ggiraph
            any::dygraphs
            any::networkD3
            any::leaflet
            any::crosstalk
            any::fontawesome
            any::knitr
      - name: Render quarto
        uses: quarto-dev/quarto-actions/render@v2
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages
          token: ${{ secrets.TOKEN }}

