project:
  type: website
  output-dir: docs

website:
  open-graph: true
  site-url: "https://royfrancis.github.io/folium/"
  image: "assets/images/seo.webp"
  description: "A quarto website template for project reports."
  favicon: "assets/favicon.png"
  navbar:
    logo: "assets/logos/nbis-scilifelab.webp"
    logo-alt: "logo"
    left:
      - text: "Home"
        href: "index.html"
  page-footer:
    border: false
    left: "{{< meta current_year >}} [NBIS](https://nbis.se)"
    right: "Published with [Quarto](https://quarto.org/) v{{< meta quarto_version >}}"
  sidebar:
    contents:
      - section: Reports
        contents: "reports/*"
      - "completion.qmd"
  bread-crumbs: false

nbis:
  id: "0000"
  client: 
    name: "John Doe"
    email: "john.doe@email.com"
    org: "Some university"
  pi:
    name: "John Doe"
    email: "john.doe@email.com"
  analyst:
    name: "John Doe"
    email: "john.doe@nbis.se"

format:
  html:
    quarto-required: ">=1.4.0"
    include-in-header: "assets/include_head.html"
    theme: "assets/css/styles.scss"
    smooth-scroll: true
    toc: true
    toc-depth: 5
    toc-location: right
    number-sections: true
    number-depth: 4
    code-fold: true
    code-tools: false
    code-copy: true
    code-overflow: wrap
    df-print: paged
    standalone: false
    fig-align: left
    title-block-banner: "assets/images/banner.png"
    author: "{{< meta nbis.analyst.name >}}"
    date:  last-modified
    date-format: "DD-MMM-YYYY"
    image: "assets/images/featured.webp"
    lightbox: auto

crossref:
  fig-title: "**Fig**"
  fig-labels: arabic
  tbl-title: "**Tab**"
  tbl-labels: arabic
  title-delim: "**:**"

execute:
  eval: true
  echo: true
  warning: false
  message: false
  freeze: false

filters:
  - assets/custom.lua
  - assets/fold-results.lua
  - fontawesome
