name: deploy
on:
  push:
    branches:
      - main
jobs:
  rmd-render-job:
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-22.04, r: '4.1.0'}
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libxml2-dev libssl-dev libcurl4-openssl-dev libudunits2-dev libopenblas-base libgdal-dev
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
      - name: Cache R packages
        id: cache-r-packages
        uses: actions/cache@v3
        with:
          path: "/home/runner/work/_temp/Library"
          key: ${{runner.os}}-${{matrix.r}}-$(ls /home/runner/work/_temp/Library/ | sha256sum)
      - name: Install R packages
        if: steps.cache-r-packages.outputs.cache-hit != 'true'
        run: |
          Rscript -e 'install.packages(c("dplyr", "tidyr", "stringr", "htmlTable", "kableExtra", "formattable", "DT", "reactable", "ggplot2", "rbokeh", "highcharter", "plotly", "ggiraph", "dygraphs", "networkD3", "leaflet", "crosstalk", "fontawesome", "knitr"), repos="https://cloud.r-project.org/")'
      - name: Setup quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.2.335
      - name: Render quarto
        uses: quarto-dev/quarto-actions/render@v2
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages
          token: ${{ secrets.TOKEN }}

